### ISSUE TITLE
image.jpg: not JPEG or PNG image (when it actually is)

### ISSUE THREAD

**Issue by motioncircus** [jarun/imgp#22] opened 2017-11-08 23:45 UTC
Hi,
While looking for a fast image resizer for a low power project, I found and installed your awesome tool on a RaspberryPi ZeroW machine running the latest version of Raspbian (Stretch).

Finding the error mentioned in the subject line, while testing an IMGP resize on one of my images, I downloaded a couple of alternative images from the Internet as comparison tests.  One PNG and one JPEG picked at random.  IMGP worked fine on those files.

The unidentifiable jpg of mine (attached below) was shot by a Canon Powershot camera and transferred to the machine using CHDK-PTP (Canon Hackers Development Kit) 

I attach the image in the hope that it may shed some light on the issue.
Thanks

![still-2017_11_09___09_57](https://user-images.githubusercontent.com/8664851/32580763-f98a2f68-c53a-11e7-8f77-b0f83b631434.jpg)

**Comment by jarun** [comment] 2017-11-09 03:14
This is an MPO file and the issue is already fixed on master at #21.

**Closed by jarun** 2017-11-09 03:14 UTC

**Comment by motioncircus** [comment] 2017-11-09 03:26
Hi Jarun,
Thanks for your swift attention.

I am rather a novice to linux programming, so I just tried to update my install to the latest version but it appears

**Comment by motioncircus** [comment] 2017-11-09 03:29
Hi Jarun,
Thanks for your swift attention.

I am rather a novice to linux programming, so I just tried to update my install to the latest version, in which, from what I understand, you have fixed the problem, by running this command

sudo apt-get install imgp

but I got the message that I already have version 2.2-1 which is the latest version.

Am I missing something?  Thanks for your kind patience and please be clear in any instructions
thanks

**Comment by jarun** [comment] 2017-11-09 04:06
Hi,

    sudo apt-get install imgp
will install the latest released version. However, the fix is still not in any release. It's in the development branch. You can get the latest dev snapshot by downloading https://github.com/jarun/imgp/archive/master.zip.

Extract the archive and run the imgp file in it using:

    ./imgp
along with your arguments.

**Comment by motioncircus** [comment] 2017-11-09 05:18
Thanks Jarun,

I did as you suggested and the programs works flawlessly when the
executable is run from that folder.

As a novice, I'm unsure of the difference between running it like this and
running an 'installed' version.

For future yous would you suggest I subscribe to the GitHub repo.. wait til
you roll out the next 'release' and then 'install' again?

Cheers

Nigel



*Nigel Haslam* *| Director *

*Motion Circus Pty Ltd. Byron Bay*
*t**: + 61 2 8007 7338 **|**m**: * *+ 61  403 020 126*
*w: www.motioncircus.com <http://www.motioncircus.com/>*
link to website <http://motioncircus.com>

**Comment by jarun** [comment] 2017-11-09 05:43
I believe you can use this for a while till next release.

Subscribing to imgp is more of a personal choice but I don't think you would want to receive mails regarding every change. When a new version is available your package manager should tell you about it.

Also, if you find it useful, please consider donating a little to encourage what we do spending our time. :)
